/* superscalar.h -- the fixed scalar C ABI. */

#pragma once

/* GENERATED by cbindgen from superscalar-ffi. DO NOT EDIT. Regenerate: crates/ffi/scripts/check_header.sh --write */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Which `ScalarValue` field is live; `Bytes` carries object scalars.
typedef enum {
  ValueKind_Str = 0,
  ValueKind_Int = 1,
  ValueKind_Float = 2,
  ValueKind_Bool = 3,
  ValueKind_Bytes = 4,
} ValueKind;

// Machine-readable error category; `None` is success, `Panic` is FFI-only
// (a caught unwind), the rest map 1:1 onto `core::ErrorKind`.
typedef enum {
  ErrorCategory_None = 0,
  ErrorCategory_Parse = 1,
  ErrorCategory_Pattern = 2,
  ErrorCategory_Length = 3,
  ErrorCategory_Range = 4,
  ErrorCategory_Enum = 5,
  ErrorCategory_Custom = 6,
  ErrorCategory_Empty = 7,
  ErrorCategory_Panic = 8,
} ErrorCategory;

// A canonical scalar value crossing the boundary; only the field selected by
// `kind` is live, the rest are zeroed. Owned pointers freed via the matching
// `*_free`.
typedef struct {
  ValueKind kind;
  // `Str`: UTF-8, NUL-terminated, `str_len` bytes (excluding the NUL).
  char *str_ptr;
  size_t str_len;
  int64_t int_val;
  double float_val;
  bool bool_val;
  // `Bytes`: `bytes_len` bytes, not NUL-terminated, bincode-encoded (not JSON).
  uint8_t *bytes_ptr;
  size_t bytes_len;
} ScalarValue;

// The result of a single scalar hook; on success `value` is live and `error`
// is null, on failure `value` is empty and `error`/`error_category` are set.
// Freed with `scalar_result_free`.
typedef struct {
  bool ok;
  ScalarValue value;
  ErrorCategory error_category;
  // Human-readable `"category: message"`; null on success.
  char *error;
} ScalarResult;

// A batch of results, owned as one allocation. Freed with
// `scalar_result_array_free`.
typedef struct {
  ScalarResult *ptr;
  size_t len;
} ScalarResultArray;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Validate shape and return the canonical normalized value.
//
// # Safety
// `input` must be null or a valid NUL-terminated C string valid for the call.
ScalarResult scalar_parse(uint32_t scalar_id, const char *input);

// Transform toward canonical form without enforcing shape.
//
// # Safety
// `input` must be null or a valid NUL-terminated C string valid for the call.
ScalarResult scalar_normalize(uint32_t scalar_id, const char *input);

// Enforce shape; on success `value` is empty (read `ok`).
//
// # Safety
// `input` must be null or a valid NUL-terminated C string valid for the call.
ScalarResult scalar_validate(uint32_t scalar_id, const char *input);

// Lenient ("flag, don't block") coercion: JSON value in, JSON value out.
//
// Unlike `scalar_parse`/`normalize`/`validate` (string in, string out), this
// carries the input and output as encoded JSON strings and reuses the same
// `ScalarResult`. `json_in` is a JSON document; on success `value` is the
// canonical coercion encoded as a JSON string (`"null"` for a null
// passthrough); on a coercion failure the core `ScalarError` is mapped onto
// `error`/`error_category` exactly as the strict hooks map theirs.
//
// # Safety
// `json_in` must be null or a valid NUL-terminated C string valid for the call.
ScalarResult scalar_coerce_lenient(uint32_t scalar_id, const char *json_in);

// Release a `ScalarResult`'s owned allocations.
//
// # Safety
// `result` must have been produced by this crate and not already freed.
void scalar_result_free(ScalarResult result);

// Batch `scalar_parse`. See `run_batch`.
//
// # Safety
// `inputs` must point to `len` valid NUL-terminated C strings.
ScalarResultArray scalar_parse_batch(uint32_t scalar_id, const char *const *inputs, size_t len);

// Batch `scalar_normalize`. See `run_batch`.
//
// # Safety
// `inputs` must point to `len` valid NUL-terminated C strings.
ScalarResultArray scalar_normalize_batch(uint32_t scalar_id, const char *const *inputs, size_t len);

// Batch `scalar_validate`. See `run_batch`.
//
// # Safety
// `inputs` must point to `len` valid NUL-terminated C strings.
ScalarResultArray scalar_validate_batch(uint32_t scalar_id, const char *const *inputs, size_t len);

// Release a `ScalarResultArray` and every result it owns.
//
// # Safety
// `array` must have been produced by a `*_batch` function and not already
// freed.
void scalar_result_array_free(ScalarResultArray array);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
