//go:build darwin && arm64

package superscalar

// Code generated by scripts/build_ffi.sh. DO NOT EDIT.
//
// The SHA-256 of the static archive this package links. Its only job is to change when
// the archive changes, so Go's build cache cannot reuse a link against a stale one.
const archiveSHA256 = "b7a4b1acba9814d7840d0e50e25d190a9669eb7861ca8b3408bfcf1af1816a6e"
