// ScalarId values are FROZEN, append-only: the C ABI keys on them. Never renumber; new scalars take the next u32.

use crate::registry::{PrimitiveKind, ScalarDef, ScalarHooks, ScalarTag};

/// A scalar's frozen u32 identity: the key the C ABI, every generated binding
/// and every conformance vector use. Built-in scalars are the associated
/// constants below; an extension mints its own from its `id_base` (see
/// `Extension`). `ScalarId(n)` is a plain constructor: whether `n` names a
/// scalar is a question for the assembled `Registry`.
#[repr(transparent)]
#[derive(
    Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Debug, serde::Serialize, serde::Deserialize,
)]
pub struct ScalarId(pub u32);

impl ScalarId {
    /// Built-in ids own `0..=BUILTIN_MAX`. Extensions start at a multiple of
    /// `EXTENSION_BLOCK`.
    pub const BUILTIN_MAX: u32 = 4095;
    pub const EXTENSION_BLOCK: u32 = 4096;

    // Ids 0..=4, 7, 30..=38, 51 and 57 are permanent holes: the scalars that
    // held them moved to a downstream extension that keeps the original values
    // (assembled with `AssembleOptions::allow_legacy_ids`). A new built-in
    // takes the next id after the highest one below, never a hole.
    pub const AUTH_JWT: ScalarId = ScalarId(5);
    pub const AUTH_PASSWORD: ScalarId = ScalarId(6);
    pub const CONTACT_EMAIL: ScalarId = ScalarId(8);
    pub const CONTACT_PHONE_NUMBER: ScalarId = ScalarId(9);
    pub const CRYPTO_RSA_PRIVATE_KEY: ScalarId = ScalarId(10);
    pub const CRYPTO_RSA_PUBLIC_KEY: ScalarId = ScalarId(11);
    pub const DESIGN_COLOR: ScalarId = ScalarId(12);
    pub const EMBEDDING_VECTOR: ScalarId = ScalarId(13);
    pub const FILE_SIZE_BYTES: ScalarId = ScalarId(14);
    pub const FINANCE_MONEY: ScalarId = ScalarId(15);
    pub const GENERIC_INT64: ScalarId = ScalarId(16);
    pub const GENERIC_JSON: ScalarId = ScalarId(17);
    pub const GENERIC_PROBABILITY: ScalarId = ScalarId(18);
    pub const GENERIC_STRING_MAP: ScalarId = ScalarId(19);
    pub const GEO_LOCATION: ScalarId = ScalarId(20);
    pub const IDENTITY_NAME: ScalarId = ScalarId(21);
    pub const IDENTITY_SLUG: ScalarId = ScalarId(22);
    pub const IDENTITY_UUID: ScalarId = ScalarId(23);
    pub const IDENTITY_USER_ID: ScalarId = ScalarId(24);
    pub const LOCALIZATION_LOCALE: ScalarId = ScalarId(25);
    pub const NETWORK_DOMAIN_NAME: ScalarId = ScalarId(26);
    pub const NETWORK_IP_ADDRESS: ScalarId = ScalarId(27);
    pub const NETWORK_URI: ScalarId = ScalarId(28);
    pub const NETWORK_URL: ScalarId = ScalarId(29);
    pub const TEMPORAL_CRON_EXPRESSION: ScalarId = ScalarId(39);
    pub const TEMPORAL_DATE: ScalarId = ScalarId(40);
    pub const TEMPORAL_DATE_TIME: ScalarId = ScalarId(41);
    pub const TEMPORAL_DURATION: ScalarId = ScalarId(42);
    pub const TEMPORAL_MILLISECONDS: ScalarId = ScalarId(43);
    pub const TEMPORAL_MONTH: ScalarId = ScalarId(44);
    pub const TEMPORAL_QUARTER: ScalarId = ScalarId(45);
    pub const TEMPORAL_QUARTER_YEAR: ScalarId = ScalarId(46);
    pub const TEMPORAL_TIME: ScalarId = ScalarId(47);
    pub const TEMPORAL_TIME_ZONE: ScalarId = ScalarId(48);
    pub const TEMPORAL_YEAR: ScalarId = ScalarId(49);
    pub const TEXT_MARKDOWN: ScalarId = ScalarId(50);
    pub const TEMPORAL_SECONDS: ScalarId = ScalarId(52);
    pub const TEMPORAL_MINUTES: ScalarId = ScalarId(53);
    pub const TEMPORAL_HOURS: ScalarId = ScalarId(54);
    pub const TEMPORAL_DAYS: ScalarId = ScalarId(55);
    /// SQL text (presence/type only; no AST validation). Append-only
    /// discriminant -- never renumber (C ABI).
    pub const TEXT_SQL: ScalarId = ScalarId(56);
    pub const CRYPTO_SHA256: ScalarId = ScalarId(58);
    /// Single DNS label (one hostname segment). Append-only discriminant --
    /// never renumber (C ABI).
    pub const NETWORK_DNS_LABEL: ScalarId = ScalarId(59);
    /// RFC 5545 RRULE, without the DTSTART a calendar object would carry beside
    /// it: the anchor instant and the zone live in their own columns on the
    /// owning row, so a rule that also carried them could disagree with them.
    /// Validity only -- expanding a rule into occurrences needs a calendar and
    /// the zone database, and happens once, server-side, in Go.
    pub const TEMPORAL_RECURRENCE_RULE: ScalarId = ScalarId(60);

    /// The frozen u32 form keyed on by the C ABI.
    pub const fn as_u32(self) -> u32 {
        self.0
    }

    /// Whether this id falls in the block reserved for built-in scalars.
    pub const fn is_builtin_block(self) -> bool {
        self.0 <= Self::BUILTIN_MAX
    }
}

impl From<u32> for ScalarId {
    fn from(value: u32) -> Self {
        ScalarId(value)
    }
}

impl From<ScalarId> for u32 {
    fn from(id: ScalarId) -> u32 {
        id.0
    }
}

/// The built-in scalar defs, in ascending id order. A new scalar's `ScalarDef`
/// is APPENDED at the end and takes the next id, never inserted alphabetically
/// and never into one of the holes listed on `ScalarId`.
/// Reached only through `Registry::builtin()`.
pub(crate) static CATALOG: [ScalarDef; 44] = [
    ScalarDef {
        id: ScalarId::AUTH_JWT,
        namespace: "Auth",
        canonical: "Auth.JWT",
        primitive: PrimitiveKind::String,
        sql_type: "TEXT",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: Some("^[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+$"),
        min_length: None,
        max_length: None,
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &[],
        description: "JSON Web Token string",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "TEXT"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::AUTH_PASSWORD,
        namespace: "Auth",
        canonical: "Auth.Password",
        primitive: PrimitiveKind::String,
        sql_type: "VARCHAR(128)",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: None,
        min_length: Some(8),
        max_length: Some(128),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &[],
        description: "User password (minimum 8 characters)",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "VARCHAR(128)"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::CONTACT_EMAIL,
        namespace: "Contact",
        canonical: "Contact.Email",
        primitive: PrimitiveKind::String,
        sql_type: "CITEXT",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::CustomLogic,
        pattern: Some("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"),
        min_length: None,
        max_length: Some(255),
        minimum: None,
        maximum: None,
        case_insensitive: true,
        reserved_words: &[],
        examples: &["test@example.com"],
        description: "An email address",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "CITEXT"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks { parse: false, normalize: true, validate: true },
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::CONTACT_PHONE_NUMBER,
        namespace: "Contact",
        canonical: "Contact.PhoneNumber",
        primitive: PrimitiveKind::String,
        sql_type: "VARCHAR(16)",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::CustomLogic,
        pattern: Some("^\\+[1-9]\\d{1,14}$"),
        min_length: None,
        max_length: Some(16),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["+1234567890"],
        description: "Phone number in E.164 format",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "VARCHAR(16)"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks { parse: false, normalize: true, validate: true },
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::CRYPTO_RSA_PRIVATE_KEY,
        namespace: "Crypto",
        canonical: "Crypto.RSAPrivateKey",
        primitive: PrimitiveKind::String,
        sql_type: "TEXT",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: Some(concat!("^-----BE", "GIN (RSA )?PRIVATE KEY-----[\\s\\S]*-----END (RSA )?PRIVATE KEY-----\\s*$")),
        min_length: None,
        max_length: None,
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &[concat!("-----BE", "GIN RSA PRIVATE KEY----------END RSA PRIVATE KEY-----")],
        description: "RSA private key in PEM format",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "TEXT"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::CRYPTO_RSA_PUBLIC_KEY,
        namespace: "Crypto",
        canonical: "Crypto.RSAPublicKey",
        primitive: PrimitiveKind::String,
        sql_type: "TEXT",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: Some(concat!("^-----BE", "GIN PUBLIC KEY-----[\\s\\S]*-----END PUBLIC KEY-----\\s*$")),
        min_length: None,
        max_length: None,
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &[concat!("-----BE", "GIN PUBLIC KEY----------END PUBLIC KEY-----")],
        description: "RSA public key in PEM format",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "TEXT"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::DESIGN_COLOR,
        namespace: "Design",
        canonical: "Design.Color",
        primitive: PrimitiveKind::String,
        sql_type: "VARCHAR(9)",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::CustomLogic,
        pattern: Some("^#[0-9A-Fa-f]{8}$"),
        min_length: None,
        max_length: Some(9),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["#FF5733FF"],
        description: "CSS color value normalized to 8-digit RGBA hex format (#RRGGBBAA)",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "VARCHAR(9)"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks { parse: false, normalize: true, validate: true },
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::EMBEDDING_VECTOR,
        namespace: "Embedding",
        canonical: "Embedding.Vector",
        primitive: PrimitiveKind::String,
        sql_type: "",
        metadata_primitive: "String",
        json_schema_type: "array",
        tag: ScalarTag::CustomLogic,
        pattern: None,
        min_length: None,
        max_length: None,
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &[],
        description: "Fixed-dimensional float32 vector",
        type_mappings: &[("typescript", "number[]"), ("python", "list[float]"), ("go", "[]float32"), ("rust", "Vec<f32>"), ("json_schema", "array")],
        file_upload: None,
        image_constraints: None,
        docstring: "Fixed-dimensional float32 embedding vector.\nPer-column dimensionality is carried by the x-vector-dim schema extension on\nthe sibling embedding artifact column; the scalar itself is dimension-agnostic.",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::FILE_SIZE_BYTES,
        namespace: "File",
        canonical: "File.SizeBytes",
        primitive: PrimitiveKind::Int,
        sql_type: "BIGINT",
        metadata_primitive: "Int",
        json_schema_type: "integer",
        tag: ScalarTag::PatternOnly,
        pattern: None,
        min_length: None,
        max_length: None,
        minimum: Some(0.0_f64),
        maximum: Some(9007199254740991.0_f64),
        case_insensitive: false,
        reserved_words: &[],
        examples: &["204800"],
        description: "File size in bytes (non-negative, BIGINT-backed)",
        type_mappings: &[("typescript", "number"), ("python", "int"), ("go", "int64"), ("rust", "i64"), ("sql", "BIGINT"), ("json_schema", "integer")],
        file_upload: None,
        image_constraints: None,
        docstring: "File size in bytes. Non-negative integer; uses BIGINT to support files up\nto JS Number.MAX_SAFE_INTEGER (~9 PB).",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::FINANCE_MONEY,
        namespace: "Finance",
        canonical: "Finance.Money",
        primitive: PrimitiveKind::Int,
        sql_type: "BIGINT",
        metadata_primitive: "Int",
        json_schema_type: "integer",
        tag: ScalarTag::PatternOnly,
        pattern: None,
        min_length: None,
        max_length: None,
        minimum: Some(0.0_f64),
        maximum: Some(9007199254740991.0_f64),
        case_insensitive: false,
        reserved_words: &[],
        examples: &["1000"],
        description: "Monetary amount in smallest currency unit (e.g., cents for USD)",
        type_mappings: &[("typescript", "number"), ("python", "int"), ("go", "int64"), ("rust", "i64"), ("sql", "BIGINT"), ("json_schema", "integer")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks { parse: true, normalize: false, validate: false },
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::GENERIC_INT64,
        namespace: "Generic",
        canonical: "Generic.Int64",
        primitive: PrimitiveKind::Int,
        sql_type: "BIGINT",
        metadata_primitive: "Int",
        json_schema_type: "integer",
        tag: ScalarTag::PatternOnly,
        pattern: None,
        min_length: None,
        max_length: None,
        // Symmetric JS safe-integer range: -(2^53 - 1) .. (2^53 - 1). The schema
        // declares both bounds; the prior `None` lost the lower bound (a latent
        // registry bug the bridge gate's digit-only regex did not catch).
        minimum: Some(-9007199254740991.0_f64),
        maximum: Some(9007199254740991.0_f64),
        case_insensitive: false,
        reserved_words: &[],
        examples: &["1000"],
        description: "Signed 64-bit integer; range bounded by JavaScript's safe-integer ceiling.",
        type_mappings: &[("typescript", "number"), ("python", "int"), ("go", "int64"), ("rust", "i64"), ("sql", "BIGINT"), ("json_schema", "integer")],
        file_upload: None,
        image_constraints: None,
        docstring: "Signed 64-bit integer. Use when a field's range exceeds the 32-bit Int\nprimitive (e.g. row counts, byte sizes). The wire-level ceiling is the\nJavaScript safe-integer max (2^53 - 1) so values cross-language without\nloss; values above that should be serialised as strings instead.",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks { parse: true, normalize: false, validate: false },
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::GENERIC_JSON,
        namespace: "Generic",
        canonical: "Generic.JSON",
        primitive: PrimitiveKind::String,
        sql_type: "JSONB",
        metadata_primitive: "String",
        json_schema_type: "object",
        tag: ScalarTag::CustomLogic,
        pattern: None,
        min_length: None,
        max_length: None,
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &[],
        description: "A JSON object represented as a string",
        type_mappings: &[("typescript", "Record<string, any>"), ("python", "dict"), ("go", "json.RawMessage"), ("rust", "serde_json::Value"), ("sql", "JSONB"), ("json_schema", "object")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::GENERIC_PROBABILITY,
        namespace: "Generic",
        canonical: "Generic.Probability",
        primitive: PrimitiveKind::Float,
        sql_type: "DOUBLE PRECISION",
        metadata_primitive: "Float",
        json_schema_type: "number",
        tag: ScalarTag::PatternOnly,
        pattern: None,
        min_length: None,
        max_length: None,
        minimum: Some(0.0_f64),
        maximum: Some(1.0_f64),
        case_insensitive: false,
        reserved_words: &[],
        examples: &["0.75"],
        description: "Probability value from 0.0 to 1.0 inclusive",
        type_mappings: &[("typescript", "number"), ("python", "float"), ("go", "float64"), ("rust", "f64"), ("sql", "DOUBLE PRECISION"), ("json_schema", "number")],
        file_upload: None,
        image_constraints: None,
        docstring: "Probability value from 0.0 to 1.0 inclusive.\nUse for calibrated likelihoods and confidence scores where 0 means impossible/absent\nand 1 means certain/present.",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::GENERIC_STRING_MAP,
        namespace: "Generic",
        canonical: "Generic.StringMap",
        primitive: PrimitiveKind::String,
        sql_type: "JSONB",
        metadata_primitive: "String",
        json_schema_type: "object",
        tag: ScalarTag::CustomLogic,
        pattern: None,
        min_length: None,
        max_length: None,
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &[],
        description: "A string-to-string map stored as JSON",
        type_mappings: &[("typescript", "Record<string, string>"), ("python", "Dict[str, str]"), ("go", "map[string]string"), ("rust", "std::collections::HashMap<String, String>"), ("sql", "JSONB"), ("json_schema", "object")],
        file_upload: None,
        image_constraints: None,
        docstring: "A string-to-string map stored as JSON. Used for metadata tags, HTTP headers,\nfield mappings, and other key-value data where both keys and values are strings.",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::GEO_LOCATION,
        namespace: "Geo",
        canonical: "Geo.Location",
        primitive: PrimitiveKind::Object,
        sql_type: "POINT",
        metadata_primitive: "String",
        json_schema_type: "object",
        tag: ScalarTag::Structural,
        pattern: Some("^-?\\d+(\\.\\d+)?,-?\\d+(\\.\\d+)?$"),
        min_length: None,
        max_length: None,
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["37.7749,-122.4194"],
        description: "Geographic location with latitude and longitude",
        type_mappings: &[("typescript", "{ lat: number; lon: number }"), ("python", "dict"), ("go", "struct{ Lat float64; Lon float64 }"), ("rust", "struct Location { lat: f64, lon: f64 }"), ("sql", "POINT"), ("json_schema", "object")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: Some("String"),
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::IDENTITY_NAME,
        namespace: "Identity",
        canonical: "Identity.Name",
        primitive: PrimitiveKind::String,
        sql_type: "VARCHAR(80)",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: None,
        min_length: Some(2),
        max_length: Some(80),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["A Name"],
        description: "An objects name",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "VARCHAR(80)"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::IDENTITY_SLUG,
        namespace: "Identity",
        canonical: "Identity.Slug",
        primitive: PrimitiveKind::String,
        sql_type: "CITEXT",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: Some("^[a-z0-9]+(?:[-_][a-z0-9]+)*$"),
        min_length: Some(1),
        max_length: Some(255),
        minimum: None,
        maximum: None,
        case_insensitive: true,
        reserved_words: &[],
        examples: &["acme-corp"],
        description: "A URL friendly version of a string",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "CITEXT"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "URL-friendly identifier for identity handles and resource labels.\nNo infrastructure-imposed 17-character restriction applies.\n\nAllows hyphens and underscores as word separators -- hyphens for URL-style\nslugs (`google-users`), underscores for SQL identifiers / data-catalog table\nnames (`q1_sales`). The two separators may also be mixed.",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::IDENTITY_UUID,
        namespace: "Identity",
        canonical: "Identity.UUID",
        primitive: PrimitiveKind::String,
        sql_type: "UUID",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::CustomLogic,
        pattern: Some("^([0-9A-Za-z]{1,22}|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$"),
        min_length: None,
        max_length: None,
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["YQJpYwUwvbaLOwTUr4thA"],
        description: "UUID v4 with automatic base62 encoding for client-facing APIs",
        type_mappings: &[("typescript", "string"), ("python", "uuid.UUID"), ("go", "uuid.UUID"), ("rust", "uuid::Uuid"), ("sql", "UUID"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "UUID v4 with automatic base62 encoding for client-facing APIs.\n\nClient-Side Format (JSON/URLs/emails):\n  - Compact base62 string without hyphens (e.g., \"YQJpYwUwvbaLOwTUr4thA\")\n  - 21 characters instead of 36 (42% smaller)\n  - URL-friendly, no special characters\n  - More readable and easier to copy/paste\n\nBackend Format (Database/Internal):\n  - Standard UUID format with hyphens (e.g., \"123e4567-e89b-12d3-a456-426614174000\")\n  - Stored as UUID type in PostgreSQL for efficient indexing\n  - Automatic conversion between formats via JSON marshaling\n\nThe Go implementation automatically handles conversion:\n  - MarshalJSON: Converts UUID -> base62 string for API responses\n  - UnmarshalJSON: Accepts both base62 and standard formats for flexibility\n  - ToUUID(): Returns standard uuid.UUID for database operations\n  - String(): Returns base62 format for client output",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks { parse: true, normalize: false, validate: false },
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::IDENTITY_USER_ID,
        namespace: "Identity",
        canonical: "Identity.UserID",
        primitive: PrimitiveKind::String,
        sql_type: "UUID",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::CustomLogic,
        pattern: Some("^[0-9A-Za-z]{1,22}$"),
        min_length: None,
        max_length: None,
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["YQJpYwUwvbaLOwTUr4thA"],
        description: "UUID v4 string as base62",
        type_mappings: &[("typescript", "string"), ("python", "uuid.UUID"), ("go", "uuid.UUID"), ("rust", "uuid::Uuid"), ("sql", "UUID"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: Some(ScalarId::IDENTITY_UUID),
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks { parse: true, normalize: false, validate: false },
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::LOCALIZATION_LOCALE,
        namespace: "Localization",
        canonical: "Localization.Locale",
        primitive: PrimitiveKind::String,
        sql_type: "VARCHAR(35)",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: Some("^[a-z]{2,3}(-[A-Z][a-z]{3})?(-[A-Z]{2})?$"),
        min_length: None,
        max_length: Some(35),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["en-US"],
        description: "BCP 47 language tag (e.g., en-US, fr-FR)",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "VARCHAR(35)"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::NETWORK_DOMAIN_NAME,
        namespace: "Network",
        canonical: "Network.DomainName",
        primitive: PrimitiveKind::String,
        sql_type: "CITEXT",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: Some("^[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?)*$"),
        min_length: None,
        max_length: Some(255),
        minimum: None,
        maximum: None,
        case_insensitive: true,
        reserved_words: &[],
        examples: &["example.com"],
        description: "Valid domain name (RFC 1035 compliant)",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "CITEXT"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::NETWORK_IP_ADDRESS,
        namespace: "Network",
        canonical: "Network.IpAddress",
        primitive: PrimitiveKind::String,
        sql_type: "INET",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: Some("^(((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$"),
        min_length: None,
        max_length: Some(45),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["192.168.1.1"],
        description: "IPv4 or IPv6 address",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "INET"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::NETWORK_URI,
        namespace: "Network",
        canonical: "Network.Uri",
        primitive: PrimitiveKind::String,
        sql_type: "TEXT",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: Some("^[a-zA-Z][a-zA-Z0-9+.-]*://[^\\s]+$"),
        min_length: None,
        max_length: Some(4096),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["postgres://user:pass@localhost:5432/dbname"],
        description: "RFC 3986 URI for connection strings and non-HTTP resources",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "TEXT"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "RFC 3986 compliant URI for connection strings and non-HTTP resources.\nSupports various schemes (postgres://, redis://, amqp://, file://, etc.)\nand formats including localhost, IP addresses, and embedded credentials.\n\nUse `Network_Url` scalar for HTTP/HTTPS web URLs with stricter validation.",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::NETWORK_URL,
        namespace: "Network",
        canonical: "Network.Url",
        primitive: PrimitiveKind::String,
        sql_type: "varchar(4096)",
        metadata_primitive: "String",
        json_schema_type: "string",
        // CustomLogic: normalize prepends `https://` when no scheme is present
        // (see core/src/scalars/network_url.rs); validation stays the catalog pattern.
        tag: ScalarTag::CustomLogic,
        pattern: Some("^https?://[\\w\\-\\{\\}]+(\\.[\\w\\-\\{\\}]+)+([:/?#][\\w\\-\\._~:/?#\\[\\]@!\\$&'\\(\\)\\*\\+,;=\\{\\}%]*)?$"),
        min_length: None,
        max_length: Some(2048),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["https://www.example.com/example/path"],
        description: "Valid HTTP/HTTPS URL",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "varchar(4096)"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEMPORAL_CRON_EXPRESSION,
        namespace: "Temporal",
        canonical: "Temporal.CronExpression",
        primitive: PrimitiveKind::String,
        sql_type: "VARCHAR(100)",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: Some("^[0-9*,\\-\\/]+\\s+[0-9*,\\-\\/]+\\s+[0-9*,\\-\\/?]+\\s+[0-9*,\\-\\/A-Za-z]+\\s+[0-9*,\\-\\/A-Za-z]+$"),
        min_length: None,
        max_length: Some(100),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["0 9 * * MON-FRI"],
        description: "Standard 5-field cron expression for scheduling",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "VARCHAR(100)"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "Standard 5-field cron expression for scheduling (minute hour day-of-month month day-of-week).",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEMPORAL_DATE,
        namespace: "Temporal",
        canonical: "Temporal.Date",
        primitive: PrimitiveKind::String,
        sql_type: "DATE",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::CustomLogic,
        pattern: None,
        min_length: None,
        max_length: Some(40),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["2025-01-01"],
        description: "Calendar date, normalized to ISO 'YYYY-MM-DD'. Accepts ISO ('2025-01-01'), slash-separated ('2025/01/15', '01/15/2025'), named-month ('January 15, 2025', 'Jan 15, 2025'), and full RFC3339 datetime (the time portion is dropped).",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "DATE"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: Some("temporal_instant"),
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEMPORAL_DATE_TIME,
        namespace: "Temporal",
        canonical: "Temporal.DateTime",
        primitive: PrimitiveKind::String,
        sql_type: "TIMESTAMPTZ",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::CustomLogic,
        pattern: None,
        min_length: None,
        max_length: None,
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["2025-01-01T12:00:00Z"],
        description: "ISO8601 datetime string. Epoch wire values keep this scalar and declare x-temporal-format (unix, unix_millis, unix_micros, unix_nanos) on the property; the unit is never guessed from digit count.",
        type_mappings: &[("typescript", "Date"), ("python", "datetime.datetime"), ("go", "time.Time"), ("rust", "chrono::DateTime<chrono::Utc>"), ("sql", "TIMESTAMPTZ"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: Some("temporal_instant"),
        hooks: ScalarHooks { parse: true, normalize: false, validate: false },
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEMPORAL_DURATION,
        namespace: "Temporal",
        canonical: "Temporal.Duration",
        primitive: PrimitiveKind::String,
        sql_type: "INTERVAL",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::CustomLogic,
        pattern: Some("^(\\d+(\\.\\d+)?(ns|us|\u{b5}s|ms|s|m|h))+$"),
        min_length: None,
        max_length: Some(32),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["30s"],
        description: "Duration for timeouts and intervals",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "time.Duration"), ("rust", "String"), ("sql", "INTERVAL"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "Duration (e.g., \"5s\", \"10m\", \"1h30m\").\nUsed for timeouts, intervals, and other time-based configuration.\nSupports units: ns (nanoseconds), us/µs (microseconds), ms (milliseconds),\ns (seconds), m (minutes), h (hours). Multiple units can be combined.",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks { parse: true, normalize: true, validate: true },
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEMPORAL_MILLISECONDS,
        namespace: "Temporal",
        canonical: "Temporal.Milliseconds",
        primitive: PrimitiveKind::Int,
        sql_type: "BIGINT",
        metadata_primitive: "Int",
        json_schema_type: "integer",
        tag: ScalarTag::PatternOnly,
        pattern: None,
        min_length: None,
        max_length: None,
        minimum: Some(-9007199254740991.0_f64),
        maximum: Some(9007199254740991.0_f64),
        case_insensitive: false,
        reserved_words: &[],
        examples: &["1000"],
        description: "Signed integer count of milliseconds: an amount of elapsed time, never a point in time. An epoch timestamp is Temporal.DateTime with x-temporal-format: unix_millis.",
        type_mappings: &[("typescript", "number"), ("python", "int"), ("go", "int64"), ("rust", "i64"), ("sql", "BIGINT"), ("json_schema", "integer")],
        file_upload: None,
        image_constraints: None,
        docstring: "Signed integer count of milliseconds: an amount of elapsed time, never a point in time (an epoch timestamp is Temporal.DateTime with x-temporal-format: unix_millis). Fields that require non-negative elapsed time must declare a minimum constraint.",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks { parse: true, normalize: false, validate: false },
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEMPORAL_MONTH,
        namespace: "Temporal",
        canonical: "Temporal.Month",
        primitive: PrimitiveKind::String,
        sql_type: "VARCHAR(2)",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::CustomLogic,
        pattern: None,
        min_length: None,
        max_length: Some(9),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["02"],
        description: "Calendar month, normalized to two-digit numeric (01-12). Accepts '2', '02', 'Feb', 'February' (case-insensitive).",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "VARCHAR(2)"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEMPORAL_QUARTER,
        namespace: "Temporal",
        canonical: "Temporal.Quarter",
        primitive: PrimitiveKind::String,
        sql_type: "VARCHAR(2)",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: Some("^[Qq][1-4]$"),
        min_length: Some(2),
        max_length: Some(2),
        minimum: None,
        maximum: None,
        case_insensitive: true,
        reserved_words: &[],
        examples: &["Q1"],
        description: "Calendar quarter (Q1-Q4)",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "VARCHAR(2)"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEMPORAL_QUARTER_YEAR,
        namespace: "Temporal",
        canonical: "Temporal.QuarterYear",
        primitive: PrimitiveKind::String,
        sql_type: "VARCHAR(7)",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::CustomLogic,
        pattern: None,
        min_length: None,
        max_length: Some(8),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["2025-Q1"],
        description: "Quarter and year, normalized to 'YYYY-Q#'. Accepts '2025-Q1', 'Q1/2025', 'Q1-2025', 'Q1-25' (2-digit years interpreted as 20XX).",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "VARCHAR(7)"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEMPORAL_TIME,
        namespace: "Temporal",
        canonical: "Temporal.Time",
        primitive: PrimitiveKind::String,
        sql_type: "TIME",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: Some("^(?:(?:[01][0-9]|2[0-3]):[0-5][0-9](?::[0-5][0-9])?|(?:0?[1-9]|1[0-2]):[0-5][0-9](?::[0-5][0-9])?\\s?[AaPp][Mm])$"),
        min_length: None,
        max_length: None,
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["12:25"],
        description: "Time of day. 24-hour 'HH:MM' or 'HH:MM:SS' (hours 00-23), or 12-hour 'H:MM'/'HH:MM' with optional ':SS' and required AM/PM suffix (hours 1-12). Seconds and the AM/PM separator space are optional.",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "TIME"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEMPORAL_TIME_ZONE,
        namespace: "Temporal",
        canonical: "Temporal.TimeZone",
        primitive: PrimitiveKind::String,
        sql_type: "VARCHAR(100)",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: Some("^(?:UTC|[A-Za-z]+/[A-Za-z_/]+)$"),
        min_length: None,
        max_length: Some(100),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["America/New_York", "UTC", "Etc/UTC"],
        description: "IANA timezone identifier (e.g., America/New_York, UTC, Etc/UTC)",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "VARCHAR(100)"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEMPORAL_YEAR,
        namespace: "Temporal",
        canonical: "Temporal.Year",
        primitive: PrimitiveKind::String,
        sql_type: "VARCHAR(4)",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: Some("^[1-9]\\d{3}$"),
        min_length: Some(4),
        max_length: Some(4),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["2025"],
        description: "Calendar year as a 4-digit string (e.g., 2025)",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "VARCHAR(4)"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEXT_MARKDOWN,
        namespace: "Text",
        canonical: "Text.Markdown",
        primitive: PrimitiveKind::String,
        sql_type: "TEXT",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: Some("^[\\s\\S]*$"),
        min_length: Some(1),
        max_length: None,
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["## Hello, World!"],
        description: "Markdown text",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "TEXT"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "Markdown text",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEMPORAL_SECONDS,
        namespace: "Temporal",
        canonical: "Temporal.Seconds",
        primitive: PrimitiveKind::Int,
        sql_type: "BIGINT",
        metadata_primitive: "Int",
        json_schema_type: "integer",
        tag: ScalarTag::PatternOnly,
        pattern: None,
        min_length: None,
        max_length: None,
        minimum: Some(-9007199254740991.0_f64),
        maximum: Some(9007199254740991.0_f64),
        case_insensitive: false,
        reserved_words: &[],
        examples: &["60"],
        description: "Signed integer count of seconds: an amount of elapsed time, never a point in time. An epoch timestamp is Temporal.DateTime with x-temporal-format: unix.",
        type_mappings: &[("typescript", "number"), ("python", "int"), ("go", "int64"), ("rust", "i64"), ("sql", "BIGINT"), ("json_schema", "integer")],
        file_upload: None,
        image_constraints: None,
        docstring: "Signed integer count of seconds: an amount of elapsed time, never a point in time (an epoch timestamp is Temporal.DateTime with x-temporal-format: unix). Values retain the source unit and are not converted to another temporal unit.",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks { parse: true, normalize: false, validate: false },
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEMPORAL_MINUTES,
        namespace: "Temporal",
        canonical: "Temporal.Minutes",
        primitive: PrimitiveKind::Int,
        sql_type: "BIGINT",
        metadata_primitive: "Int",
        json_schema_type: "integer",
        tag: ScalarTag::PatternOnly,
        pattern: None,
        min_length: None,
        max_length: None,
        minimum: Some(-9007199254740991.0_f64),
        maximum: Some(9007199254740991.0_f64),
        case_insensitive: false,
        reserved_words: &[],
        examples: &["5"],
        description: "Signed integer count of minutes: an amount of elapsed time, never a point in time.",
        type_mappings: &[("typescript", "number"), ("python", "int"), ("go", "int64"), ("rust", "i64"), ("sql", "BIGINT"), ("json_schema", "integer")],
        file_upload: None,
        image_constraints: None,
        docstring: "Signed integer count of minutes: an amount of elapsed time, never a point in time. Values retain the source unit and are not converted to another temporal unit.",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks { parse: true, normalize: false, validate: false },
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEMPORAL_HOURS,
        namespace: "Temporal",
        canonical: "Temporal.Hours",
        primitive: PrimitiveKind::Int,
        sql_type: "BIGINT",
        metadata_primitive: "Int",
        json_schema_type: "integer",
        tag: ScalarTag::PatternOnly,
        pattern: None,
        min_length: None,
        max_length: None,
        minimum: Some(-9007199254740991.0_f64),
        maximum: Some(9007199254740991.0_f64),
        case_insensitive: false,
        reserved_words: &[],
        examples: &["2"],
        description: "Signed integer count of hours: an amount of elapsed time, never a point in time.",
        type_mappings: &[("typescript", "number"), ("python", "int"), ("go", "int64"), ("rust", "i64"), ("sql", "BIGINT"), ("json_schema", "integer")],
        file_upload: None,
        image_constraints: None,
        docstring: "Signed integer count of hours: an amount of elapsed time, never a point in time. Values retain the source unit and are not converted to another temporal unit.",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks { parse: true, normalize: false, validate: false },
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEMPORAL_DAYS,
        namespace: "Temporal",
        canonical: "Temporal.Days",
        primitive: PrimitiveKind::Int,
        sql_type: "BIGINT",
        metadata_primitive: "Int",
        json_schema_type: "integer",
        tag: ScalarTag::PatternOnly,
        pattern: None,
        min_length: None,
        max_length: None,
        minimum: Some(-9007199254740991.0_f64),
        maximum: Some(9007199254740991.0_f64),
        case_insensitive: false,
        reserved_words: &[],
        examples: &["7"],
        description: "Signed integer count of days: an amount of elapsed time, never a point in time or a calendar date.",
        type_mappings: &[("typescript", "number"), ("python", "int"), ("go", "int64"), ("rust", "i64"), ("sql", "BIGINT"), ("json_schema", "integer")],
        file_upload: None,
        image_constraints: None,
        docstring: "Signed integer count of days: an amount of elapsed time, never a point in time or a calendar date. Values retain the source unit and are not converted to another temporal unit.",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks { parse: true, normalize: false, validate: false },
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::TEXT_SQL,
        namespace: "Text",
        canonical: "Text.Sql",
        primitive: PrimitiveKind::String,
        sql_type: "TEXT",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: Some("^[\\s\\S]*$"),
        min_length: Some(1),
        max_length: None,
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["SELECT 1"],
        description: "SQL text",
        type_mappings: &[("typescript", "string"), ("python", "str"), ("go", "string"), ("rust", "String"), ("sql", "TEXT"), ("json_schema", "string")],
        file_upload: None,
        image_constraints: None,
        docstring: "SQL text. Presence and type only; does not parse or validate SQL syntax.",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::CRYPTO_SHA256,
        namespace: "Crypto",
        canonical: "Crypto.SHA256",
        primitive: PrimitiveKind::String,
        sql_type: "VARCHAR(64)",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::PatternOnly,
        pattern: Some("^[0-9a-f]{64}$"),
        min_length: Some(64),
        max_length: Some(64),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"],
        description: "Lowercase hexadecimal SHA-256 digest",
        type_mappings: &[
            ("typescript", "string"),
            ("python", "str"),
            ("go", "string"),
            ("rust", "String"),
            ("sql", "VARCHAR(64)"),
            ("json_schema", "string"),
        ],
        file_upload: None,
        image_constraints: None,
        docstring: "A 32-byte SHA-256 digest encoded as exactly 64 lowercase hexadecimal characters.",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    ScalarDef {
        id: ScalarId::NETWORK_DNS_LABEL,
        namespace: "Network",
        canonical: "Network.DnsLabel",
        primitive: PrimitiveKind::String,
        sql_type: "CITEXT",
        metadata_primitive: "String",
        json_schema_type: "string",
        tag: ScalarTag::CustomLogic,
        pattern: Some("^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?$"),
        min_length: None,
        max_length: Some(63),
        minimum: None,
        maximum: None,
        case_insensitive: true,
        reserved_words: &[],
        examples: &["mycompany"],
        description: "Single DNS label (RFC 1035): one hostname segment, no dots",
        type_mappings: &[
            ("typescript", "string"),
            ("python", "str"),
            ("go", "string"),
            ("rust", "String"),
            ("sql", "CITEXT"),
            ("json_schema", "string"),
        ],
        file_upload: None,
        image_constraints: None,
        docstring: "Single DNS label: 1-63 characters, alphanumeric edges, hyphens inside, both cases accepted and preserved.\n\nNormalize trims, keeps an already-valid label unchanged, strips a leading http(s) scheme and any path, and takes the first label of a pasted multi-label hostname (a port or foreign character disqualifies the extraction). Validate is strict on the raw input.",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
    // APPENDED, not filed beside the other Temporal.* entries: `index()` reads
    // both ALL and CATALOG, so an alphabetical insert would desync every later
    // entry from its discriminant and silently mis-resolve those scalars.
    ScalarDef {
        id: ScalarId::TEMPORAL_RECURRENCE_RULE,
        namespace: "Temporal",
        canonical: "Temporal.RecurrenceRule",
        primitive: PrimitiveKind::String,
        sql_type: "VARCHAR(512)",
        metadata_primitive: "String",
        json_schema_type: "string",
        // The grammar is a part list with cross-part rules (UNTIL excludes
        // COUNT, BYSETPOS needs another BY rule), which no regex states, so
        // there is no declared pattern for the parity gate to check.
        tag: ScalarTag::CustomLogic,
        pattern: None,
        min_length: Some(6),
        max_length: Some(512),
        minimum: None,
        maximum: None,
        case_insensitive: false,
        reserved_words: &[],
        examples: &["FREQ=WEEKLY;BYMINUTE=0;BYHOUR=9;BYDAY=MO,WE,FR"],
        description: "RFC 5545 recurrence rule, without DTSTART",
        type_mappings: &[
            ("typescript", "string"),
            ("python", "str"),
            ("go", "string"),
            ("rust", "String"),
            ("sql", "VARCHAR(512)"),
            ("json_schema", "string"),
        ],
        file_upload: None,
        image_constraints: None,
        docstring: "An RFC 5545 RRULE such as \"FREQ=WEEKLY;BYDAY=MO,WE,FR\".\nCarries no DTSTART: the anchor instant and the timezone live in their own\ncolumns on the owning row, so a rule cannot disagree with them. Normalizes to\ncanonical part order with sorted lists, so the same schedule is always the same\nstring. Validity only -- expanding a rule into occurrences happens server-side.",
        alias_of: None,
        schema_primitive_override: None,
        schema_omit: false,
        format: None,
        reserved_words_case_insensitive: false,
        reserved_words_match_partial: false,
        comparability_class: None,
        hooks: ScalarHooks::NONE,
        metadata_omit: false,
    },
];
