// @generated; do not edit

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ScalarMetadata {
    pub canonical_name: &'static str,
    pub primitive: &'static str,
    pub sql_type: &'static str,
    pub json_schema_type: Option<&'static str>,
    pub format: Option<&'static str>,
    pub max_length: Option<usize>,
    pub min_length: Option<usize>,
    pub pattern: Option<&'static str>,
    /// Comparability equivalence class, `None` when the scalar has none.
    /// Field equality is NOT the comparability relation: two `None`s compare
    /// equal, so a direct comparison answers `true` for every pair of unclassed
    /// scalars. The relation is `ScalarDef::comparable_with`.
    pub comparability_class: Option<&'static str>,
    pub is_sortable: bool,
}

pub const SCALAR_METADATA: &[ScalarMetadata] = &[
    ScalarMetadata {
        canonical_name: "Auth.JWT",
        primitive: "String",
        sql_type: "TEXT",
        json_schema_type: Some("string"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: Some("^[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Auth.Password",
        primitive: "String",
        sql_type: "VARCHAR(128)",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(128),
        min_length: Some(8),
        pattern: None,
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Contact.Email",
        primitive: "String",
        sql_type: "CITEXT",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(255),
        min_length: None,
        pattern: Some("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Contact.PhoneNumber",
        primitive: "String",
        sql_type: "VARCHAR(16)",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(16),
        min_length: None,
        pattern: Some("^\\+[1-9]\\d{1,14}$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Crypto.RSAPrivateKey",
        primitive: "String",
        sql_type: "TEXT",
        json_schema_type: Some("string"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: Some("^-----BEGIN (RSA )?PRIVATE KEY-----[\\s\\S]*-----END (RSA )?PRIVATE KEY-----\\s*$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Crypto.RSAPublicKey",
        primitive: "String",
        sql_type: "TEXT",
        json_schema_type: Some("string"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: Some("^-----BEGIN PUBLIC KEY-----[\\s\\S]*-----END PUBLIC KEY-----\\s*$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Design.Color",
        primitive: "String",
        sql_type: "VARCHAR(9)",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(9),
        min_length: None,
        pattern: Some("^#[0-9A-Fa-f]{8}$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Embedding.Vector",
        primitive: "String",
        sql_type: "",
        json_schema_type: Some("array"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: None,
        comparability_class: None,
        is_sortable: false,
    },
    ScalarMetadata {
        canonical_name: "File.SizeBytes",
        primitive: "Int",
        sql_type: "BIGINT",
        json_schema_type: Some("integer"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: None,
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Finance.Money",
        primitive: "Int",
        sql_type: "BIGINT",
        json_schema_type: Some("integer"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: None,
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Generic.Int64",
        primitive: "Int",
        sql_type: "BIGINT",
        json_schema_type: Some("integer"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: None,
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Generic.JSON",
        primitive: "String",
        sql_type: "JSONB",
        json_schema_type: Some("object"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: None,
        comparability_class: None,
        is_sortable: false,
    },
    ScalarMetadata {
        canonical_name: "Generic.Probability",
        primitive: "Float",
        sql_type: "DOUBLE PRECISION",
        json_schema_type: Some("number"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: None,
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Generic.StringMap",
        primitive: "String",
        sql_type: "JSONB",
        json_schema_type: Some("object"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: None,
        comparability_class: None,
        is_sortable: false,
    },
    ScalarMetadata {
        canonical_name: "Geo.Location",
        primitive: "String",
        sql_type: "POINT",
        json_schema_type: Some("object"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: Some("^-?\\d+(\\.\\d+)?,-?\\d+(\\.\\d+)?$"),
        comparability_class: None,
        is_sortable: false,
    },
    ScalarMetadata {
        canonical_name: "Identity.Name",
        primitive: "String",
        sql_type: "VARCHAR(80)",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(80),
        min_length: Some(2),
        pattern: None,
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Identity.Slug",
        primitive: "String",
        sql_type: "CITEXT",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(255),
        min_length: Some(1),
        pattern: Some("^[a-z0-9]+(?:[-_][a-z0-9]+)*$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Identity.UUID",
        primitive: "String",
        sql_type: "UUID",
        json_schema_type: Some("string"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: Some("^([0-9A-Za-z]{1,22}|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Identity.UserID",
        primitive: "String",
        sql_type: "UUID",
        json_schema_type: Some("string"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: Some("^[0-9A-Za-z]{1,22}$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Localization.Locale",
        primitive: "String",
        sql_type: "VARCHAR(35)",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(35),
        min_length: None,
        pattern: Some("^[a-z]{2,3}(-[A-Z][a-z]{3})?(-[A-Z]{2})?$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Network.DomainName",
        primitive: "String",
        sql_type: "CITEXT",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(255),
        min_length: None,
        pattern: Some("^[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?)*$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Network.IpAddress",
        primitive: "String",
        sql_type: "INET",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(45),
        min_length: None,
        pattern: Some("^(((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Network.Uri",
        primitive: "String",
        sql_type: "TEXT",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(4096),
        min_length: None,
        pattern: Some("^[a-zA-Z][a-zA-Z0-9+.-]*://[^\\s]+$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Network.Url",
        primitive: "String",
        sql_type: "varchar(4096)",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(2048),
        min_length: None,
        pattern: Some("^https?://[\\w\\-\\{\\}]+(\\.[\\w\\-\\{\\}]+)+([:/?#][\\w\\-\\._~:/?#\\[\\]@!\\$&'\\(\\)\\*\\+,;=\\{\\}%]*)?$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Temporal.CronExpression",
        primitive: "String",
        sql_type: "VARCHAR(100)",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(100),
        min_length: None,
        pattern: Some("^[0-9*,\\-\\/]+\\s+[0-9*,\\-\\/]+\\s+[0-9*,\\-\\/?]+\\s+[0-9*,\\-\\/A-Za-z]+\\s+[0-9*,\\-\\/A-Za-z]+$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Temporal.Date",
        primitive: "String",
        sql_type: "DATE",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(40),
        min_length: None,
        pattern: None,
        comparability_class: Some("temporal_instant"),
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Temporal.DateTime",
        primitive: "String",
        sql_type: "TIMESTAMPTZ",
        json_schema_type: Some("string"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: None,
        comparability_class: Some("temporal_instant"),
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Temporal.Duration",
        primitive: "String",
        sql_type: "INTERVAL",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(32),
        min_length: None,
        pattern: Some("^(\\d+(\\.\\d+)?(ns|us|µs|ms|s|m|h))+$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Temporal.Milliseconds",
        primitive: "Int",
        sql_type: "BIGINT",
        json_schema_type: Some("integer"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: None,
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Temporal.Month",
        primitive: "String",
        sql_type: "VARCHAR(2)",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(9),
        min_length: None,
        pattern: None,
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Temporal.Quarter",
        primitive: "String",
        sql_type: "VARCHAR(2)",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(2),
        min_length: Some(2),
        pattern: Some("^[Qq][1-4]$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Temporal.QuarterYear",
        primitive: "String",
        sql_type: "VARCHAR(7)",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(8),
        min_length: None,
        pattern: None,
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Temporal.Time",
        primitive: "String",
        sql_type: "TIME",
        json_schema_type: Some("string"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: Some("^(?:(?:[01][0-9]|2[0-3]):[0-5][0-9](?::[0-5][0-9])?|(?:0?[1-9]|1[0-2]):[0-5][0-9](?::[0-5][0-9])?\\s?[AaPp][Mm])$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Temporal.TimeZone",
        primitive: "String",
        sql_type: "VARCHAR(100)",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(100),
        min_length: None,
        pattern: Some("^(?:UTC|[A-Za-z]+/[A-Za-z_/]+)$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Temporal.Year",
        primitive: "String",
        sql_type: "VARCHAR(4)",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(4),
        min_length: Some(4),
        pattern: Some("^[1-9]\\d{3}$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Text.Markdown",
        primitive: "String",
        sql_type: "TEXT",
        json_schema_type: Some("string"),
        format: None,
        max_length: None,
        min_length: Some(1),
        pattern: Some("^[\\s\\S]*$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Temporal.Seconds",
        primitive: "Int",
        sql_type: "BIGINT",
        json_schema_type: Some("integer"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: None,
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Temporal.Minutes",
        primitive: "Int",
        sql_type: "BIGINT",
        json_schema_type: Some("integer"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: None,
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Temporal.Hours",
        primitive: "Int",
        sql_type: "BIGINT",
        json_schema_type: Some("integer"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: None,
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Temporal.Days",
        primitive: "Int",
        sql_type: "BIGINT",
        json_schema_type: Some("integer"),
        format: None,
        max_length: None,
        min_length: None,
        pattern: None,
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Text.Sql",
        primitive: "String",
        sql_type: "TEXT",
        json_schema_type: Some("string"),
        format: None,
        max_length: None,
        min_length: Some(1),
        pattern: Some("^[\\s\\S]*$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Crypto.SHA256",
        primitive: "String",
        sql_type: "VARCHAR(64)",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(64),
        min_length: Some(64),
        pattern: Some("^[0-9a-f]{64}$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Network.DnsLabel",
        primitive: "String",
        sql_type: "CITEXT",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(63),
        min_length: None,
        pattern: Some("^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?$"),
        comparability_class: None,
        is_sortable: true,
    },
    ScalarMetadata {
        canonical_name: "Temporal.RecurrenceRule",
        primitive: "String",
        sql_type: "VARCHAR(512)",
        json_schema_type: Some("string"),
        format: None,
        max_length: Some(512),
        min_length: Some(6),
        pattern: None,
        comparability_class: None,
        is_sortable: true,
    },
];

impl ScalarMetadata {
    /// Flat (single-identifier) form of the canonical name, e.g.
    /// "Contact.Email" -> "Contact_Email". Used where dotted names are not
    /// valid identifiers (runtime schema payload keys, Arrow metadata).
    pub fn flat_name(&self) -> String {
        flat_scalar_name(self.canonical_name)
    }
}

/// Derive the flat scalar name from a canonical name ("A.B" -> "A_B").
/// Canonical segments are PascalCase and never contain underscores, so the
/// mapping is bijective.
pub fn flat_scalar_name(canonical_name: &str) -> String {
    canonical_name.replace('.', "_")
}

pub fn scalar_metadata_by_canonical_name(name: &str) -> Option<&'static ScalarMetadata> {
    SCALAR_METADATA
        .iter()
        .find(|scalar| scalar.canonical_name == name)
}
